[package]
name = "ocpp-charge-point-simulator"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.45.0", features = ["full"] }
tokio-tungstenite = "0.26.2"
tungstenite = "0.26.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
uuid = { version = "1.16.0", features = ["v4"] }
rust-ocpp = "3.0.1"
tracing-subscriber = "0.3.19"
tracing = "0.1.41"
dotenvy = "0.15.7"
url = "2.5.4"
anyhow = "1.0.98"
futures-util = "0.3.31"
chrono = "0.4.41"
