[package]
name = "common"
version = "0.0.1"
edition = "2024"

[dependencies]
tokio = { version = "1.45.0", features = ["full"] }
toml = "0.8.22"
anyhow = "1.0.98"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
uuid = { version = "1.16.0", features = ["v4", "serde"] }
